# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 43bb3b0a1f71b52dc203857325c13449c4f631276fc34768e92a7381c616ad7a65296b98311e48170fbedf0c181adf6c12305ea179d878fbfb26c7846b86bccd

test:
  secret_key_base: 8b1ee7facf3e83260a14cc371a048771cedfee07d84b8c5f91be6a58d9be167c66f16f6b24c71da8b78d8a7ecbc05f034d94fd07b52328dd2276f0754c62300b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
